name: STAGING - Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  setup-build-publish-deploy:
    timeout-minutes: 45
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v2
        with:
          ref: 'master'
          path: './backend'
          token: ${{secrets.GIT_REPO_TOKEN}}
      - name: Checkout Frontend
        uses: actions/checkout@v2
        with:
          repository: AndreLami/TestFrontDeploy
          ref: 'master'
          path: './frontend'
          token: ${{secrets.GIT_REPO_TOKEN}}
      - name: Build Backend
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET  }}
        run: |
          echo "Hello world $TEST_SECRET"
          ls ./
      - name: Docker Test
        run: docker ps

      - name: Build Backend
        run: |
          docker build ./backend -t checkinch_backend
          docker save checkinch_backend > checkinch_backend.tar

      - name: Build Frontend
          run: |
            docker build ./frontend -t checkinch_frontend
            docker save checkinch_frontend > checkinch_frontend.tar
            ls

      - name: Prepare Remote Private Key
        env:
          REMOTE_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
        run: |
          echo "$REMOTE_PRIVATE_KEY" > private_key && chmod 600 private_key

      - name: Clear Images Directory
          env:
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
          run: |
            ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USERNAME}@${REMOTE_HOST} '
              rm -r ./Deploy/images
            '
