name: STAGING - Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  setup-build-publish-deploy:
    timeout-minutes: 45
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v2
        with:
          ref: 'master'
          path: './backend'
          token: ${{secrets.GIT_REPO_TOKEN}}

      - name: Checkout Frontend
        uses: actions/checkout@v2
        with:
          repository: AndreLami/TestFrontDeploy
          ref: 'master'
          path: './frontend'
          token: ${{secrets.GIT_REPO_TOKEN}}

      - name: Build Backend
        run: |
          docker build ./backend -t backend_image
          docker save backend_image > backend_image.tar

      - name: Build Frontend
        run: |
          docker build ./frontend -t frontend_image
          docker save frontend_image > frontend_image.tar
          ls

      - name: Prepare Remote Private Key
        env:
          REMOTE_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
        run: |
          echo "$REMOTE_PRIVATE_KEY" > private_key && chmod 600 private_key

      - name: Deploy
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USERNAME}@${REMOTE_HOST} '
            rm -r ./Deploy/images
            mkdir ./Deploy/images
          '

          scp -o StrictHostKeyChecking=no -i private_key ./backend_image.tar ${REMOTE_USERNAME}@${REMOTE_HOST}:./Deploy/images/backend_image.tar
          scp -o StrictHostKeyChecking=no -i private_key ./frontend_image.tar ${REMOTE_USERNAME}@${REMOTE_HOST}:./Deploy/images/frontend_image.tar

          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USERNAME}@${REMOTE_HOST} '
            cd ./Deploy
            ./deploy.sh
          '
